### GET all
GET http://localhost:3001/api/persons

### GET info
GET http://localhost:3001/info

### GET single person
GET http://localhost:3001/api/persons/2

### DELETE single person
DELETE http://localhost:3001/api/persons/5

### POST new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "marco",
    "number": "34-45-567890"
}

