GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Il mio primo blog",
  "author": "Andrea",
  "url": "http://example.com",
  "likes": 10
}
